#!/usr/bin/env python3
"""Rasterise DejaVu Sans Bold into 4-bit anti-aliased glyphs -> app/font.h.

Only needed if you want to change the fonts; font.h is checked in.
Usage: python3 mkfont.py /path/to/DejaVuSans-Bold.ttf > ../app/font.h
"""
import sys
from PIL import Image, ImageDraw, ImageFont

TTF = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
SIZES = [("small", 13), ("medium", 17), ("large", 26)]

out = ["/* Generated by tools/mkfont.py from DejaVu Sans Bold (Bitstream Vera license). */",
       "#include <stdint.h>",
       "typedef struct { uint16_t off; uint8_t w, h; int8_t xo, yo; uint8_t adv; } glyph_t;",
       "typedef struct { uint8_t height, ascent; const glyph_t *g; const uint8_t *bits; } font_t;"]
for name, px in SIZES:
    f = ImageFont.truetype(TTF, px)
    ascent, descent = f.getmetrics()
    glyphs, data = [], bytearray()
    for c in range(32, 127):
        ch = chr(c)
        adv = round(f.getlength(ch))
        bbox = f.getbbox(ch)
        if bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
            glyphs.append((len(data), 0, 0, 0, 0, adv))
            continue
        x0, y0, x1, y1 = bbox
        w, h = x1 - x0, y1 - y0
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((-x0, -y0), ch, font=f, fill=255)
        px4 = [(v + 8) // 17 for v in img.getdata()]  # 0..15
        if len(px4) % 2:
            px4.append(0)
        off = len(data)
        for i in range(0, len(px4), 2):
            data.append((px4[i] << 4) | px4[i + 1])
        glyphs.append((off, w, h, x0, y0, adv))
    out.append(f"static const uint8_t {name}_bits[] = {{")
    for i in range(0, len(data), 24):
        out.append("  " + ",".join(str(b) for b in data[i:i + 24]) + ",")
    out.append("};")
    out.append(f"static const glyph_t {name}_glyphs[95] = {{")
    for g in glyphs:
        out.append("  {%d,%d,%d,%d,%d,%d}," % g)
    out.append("};")
    out.append(f"static const font_t font_{name} = {{{ascent + descent}, {ascent}, {name}_glyphs, {name}_bits}};")
print("\n".join(out))
